<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;

class AdvertismentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('advertisments')->delete();
       
            $advertisments = array(
                array('id' => '7','user_id' => '3','featured_image' => 'https://drive.google.com/uc?id=1ADR5NGTHICs-8NgF4TaEG6P5oAWzkEsq&export=media','first_image' => 'https://drive.google.com/uc?id=1Ayx4K6EtN1UBVgcIsJhk7cm3yjdUj57K&export=media','second_image' => 'https://drive.google.com/uc?id=19CYCCECuTYWg9Gqy1oB46WMG-JlZttqX&export=media','category_id' => '13','subcategory_id' => '12','childcategory_id' => '7','name' => 'Pizza peperoni','slug' => 'pizza-peperoni','description' => 'Pizza peperoni','price' => '55','price_status' => 'fixed','product_condition' => 'new','listing_location' => 'Pizza peperoni','country_id' => '4','state_id' => '165','city_id' => '6433','phone_number' => '555','published' => '1','link' => 'Pizza peperoni','created_at' => '2022-05-20 12:55:58','updated_at' => '2022-05-28 14:20:48'),
                array('id' => '8','user_id' => '3','featured_image' => 'https://drive.google.com/uc?id=18D9ohIlMf8iWmvxXkWLuXL0wC7xoSMPe&export=media','first_image' => 'https://drive.google.com/uc?id=1_Htxku6jkwvZtnrXxpv9DQdszh1pH6Wp&export=media','second_image' => 'https://drive.google.com/uc?id=11R8fDd768UXiajNaPY5-QD6KfrB8PMbj&export=media','category_id' => '13','subcategory_id' => '12','childcategory_id' => '8','name' => 'big mac','slug' => 'big-mac','description' => 'big mac','price' => '33','price_status' => 'fixed','product_condition' => 'new','listing_location' => 'big mac','country_id' => '12','state_id' => '244','city_id' => '6554','phone_number' => '44','published' => '1','link' => 'big mac','created_at' => '2022-05-20 12:57:07','updated_at' => '2022-05-28 14:22:17'),
                array('id' => '9','user_id' => '3','featured_image' => 'https://drive.google.com/uc?id=1DVTy30uAv7oi3DxAUkSHp0rtk5luZb1G&export=media','first_image' => 'https://drive.google.com/uc?id=1OacxI7oGt3pBOxH8VsWnCBkgXENQ-I8k&export=media','second_image' => 'https://drive.google.com/uc?id=18rcx3HSeqi9oq2y6rOrRHJA6i2929y1O&export=media','category_id' => '13','subcategory_id' => '12','childcategory_id' => '8','name' => 'chicken burger','slug' => 'chicken-burger','description' => 'chicken burger','price' => '66','price_status' => 'fixed','product_condition' => 'new','listing_location' => 'ettt','country_id' => '12','state_id' => '244','city_id' => '6554','phone_number' => '666','published' => '1','link' => 'https://www.youtube.com/watch?v=elsrDVe4yOw','created_at' => '2022-05-20 14:43:37','updated_at' => '2022-05-28 14:23:13'),
                array('id' => '10','user_id' => '3','featured_image' => 'https://drive.google.com/uc?id=1yhi0cWthmtJdR_wFBDoHPhtuaFWMcB4y&export=media','first_image' => 'https://drive.google.com/uc?id=1vxGW1EQEXz76JtlQiQoFf3Fi0NgYH80d&export=media','second_image' => 'https://drive.google.com/uc?id=1GVWF46AyU0crlHd1pS5609Z1gyyPogUH&export=media','category_id' => '14','subcategory_id' => '13','childcategory_id' => '9','name' => 'strawberry smoothie','slug' => 'strawberry-smoothie','description' => 'strawberry smoothie','price' => '66','price_status' => 'fixed','product_condition' => 'new','listing_location' => 'ttt','country_id' => '12','state_id' => '244','city_id' => '6554','phone_number' => '66','published' => '1','link' => 'strawberry smoothie','created_at' => '2022-05-20 15:00:13','updated_at' => '2022-05-28 14:24:01'),
                array('id' => '11','user_id' => '3','featured_image' => 'https://drive.google.com/uc?id=14lIjWPyk7c5RoKP3Lwld1yHp6CyV0kMA&export=media','first_image' => 'https://drive.google.com/uc?id=1OjTS5J1Vk5OiwxvH1eE040sLIzL0kUcu&export=media','second_image' => 'https://drive.google.com/uc?id=1HEaxMflGyqxwBxHmLENjYZimEBz-CMhX&export=media','category_id' => '14','subcategory_id' => '13','childcategory_id' => '9','name' => 'cola','slug' => 'cola','description' => 'cola','price' => '55','price_status' => 'fixed','product_condition' => 'new','listing_location' => 'ff','country_id' => '12','state_id' => '244','city_id' => '6554','phone_number' => '55','published' => '0','link' => 'cola','created_at' => '2022-05-20 15:03:18','updated_at' => '2022-05-28 14:27:49'),
                array('id' => '12','user_id' => '3','featured_image' => 'https://drive.google.com/uc?id=1KdGzJGIKJHa25wKIeyBNBMT-Ecojug01&export=media','first_image' => 'https://drive.google.com/uc?id=1ewwIff3JznKINOxw9FZAiUjPFjt6QuCg&export=media','second_image' => 'https://drive.google.com/uc?id=1IqDHnrxSIaAMl4351onj8Tc2oDXNENna&export=media','category_id' => '20','subcategory_id' => '15','childcategory_id' => '11','name' => 'chocolate cheese cake','slug' => 'chocolate-cheese-cake','description' => 'chocolate cheese cake','price' => '77','price_status' => 'fixed','product_condition' => 'new','listing_location' => 'chocolate cheese cake','country_id' => '12','state_id' => '244','city_id' => '6554','phone_number' => '66','published' => '1','link' => 'chocolate cheese cake','created_at' => '2022-05-20 15:48:37','updated_at' => '2022-05-28 14:29:24'),
                array('id' => '13','user_id' => '3','featured_image' => 'https://drive.google.com/uc?id=1dyuwNVIcciRRVs6SFJr-1tmZHkesNQ3I&export=media','first_image' => 'https://drive.google.com/uc?id=1IMWoNwCZ0uc-kTTFStdnVB1E_nqSb90Q&export=media','second_image' => 'https://drive.google.com/uc?id=1bVxj3trN0XrSDRIZNJxdsrw7zkEUwjsU&export=media','category_id' => '13','subcategory_id' => '12','childcategory_id' => '7','name' => 'steak','slug' => 'steak','description' => 'steak cuts
              Good quality steak cuts work best to make Steakhouse Steak at home: boneless Ribeye (Australian Scotch Fillet), New York Strip (Australian Porterhouse) and Eye fillet are the best choices, followed by Sirloin or Australian Rump. All of these cuts are shown throughout this post to give you the BEST steak recipe.
              
              how to cook steak in a pan
              Start with close to room temperature steaks and pat dry with paper towel.
              Preheat your pan until smoking. Cast iron skillet is preferable or a heavy-duty, thick-based frying pan.
              Drizzle oil into your pan
              Season steaks with salt and pepper just before they go into your pan.
              Sear one or two steaks at a time to get a nice sear.','price' => '55','price_status' => 'fixed','product_condition' => 'likenew','listing_location' => 'tt','country_id' => '11','state_id' => '240','city_id' => '6546','phone_number' => '66','published' => '1','link' => '66','created_at' => '2022-05-20 19:30:58','updated_at' => '2022-05-28 14:30:24'),
                array('id' => '14','user_id' => '3','featured_image' => 'https://drive.google.com/uc?id=1GevP5xpozK7nYmAmhXOzgpGf-0rGNKS9&export=media','first_image' => 'https://drive.google.com/uc?id=1hzfk94IuY9mx34kyPE-vJOizVfggfL4W&export=media','second_image' => 'https://drive.google.com/uc?id=1TvZBzLKcfdvdplhSVcor0n-S3YmCo7Rg&export=media','category_id' => '13','subcategory_id' => '12','childcategory_id' => '8','name' => 'onion rings','slug' => 'onion-rings','description' => 'An onion ring, also called a French fried onion ring, is a form of appetizer or side dish in British and American cuisine. They generally consist of a cross-sectional "ring" of onion dipped in batter or bread crumbs and then deep fried; a variant is made with onion paste. Wikipedia','price' => '33','price_status' => 'fixed','product_condition' => 'heavilyused','listing_location' => 'vvv','country_id' => '12','state_id' => '244','city_id' => '6554','phone_number' => '555','published' => '1','link' => 'vvvv','created_at' => '2022-05-20 19:49:59','updated_at' => '2022-05-28 14:31:43'),
                array('id' => '15','user_id' => '3','featured_image' => 'https://drive.google.com/uc?id=17nzPXSpY35PimUkukEYjJZEhOpnhIKs1&export=media','first_image' => 'https://drive.google.com/uc?id=14bzJjahPCBdoC6o8rRT4iX3IsXWwg6ez&export=media','second_image' => 'https://drive.google.com/uc?id=1xfIHV3G9CuomVV7FFhkyFC61Y98nARlU&export=media','category_id' => '13','subcategory_id' => '12','childcategory_id' => '8','name' => 'Chocolate Mousse','slug' => 'chocolate-mousse','description' => 'A classic, proper Chocolate Mousse recipe
              I’ve never been 100% happy with the various chocolate mousse recipes I’ve tried in my lifetime. Not fluffy enough, not chocolatey enough, too sweet, grainy, etc etc. Many “easy” chocolate mousse recipes tend to use too much cream so the end result is more like custard, rather than aerated like real chocolate mousse should be.
              
              Thus, when Chocolate Mousse was submitted by a reader as a Recipe Request, I had reason to focus and make it over and over again until it was exactly what I wanted.','price' => '66','price_status' => 'fixed','product_condition' => 'likenew','listing_location' => 'rr','country_id' => '11','state_id' => '240','city_id' => '6546','phone_number' => '666','published' => '1','link' => 'https://www.youtube.com/watch?v=pGo-1MHk7c8','created_at' => '2022-05-21 18:06:45','updated_at' => '2022-05-28 14:32:40'),
                array('id' => '16','user_id' => '6','featured_image' => 'https://drive.google.com/uc?id=1-CM7LKF_eiRKwrj0oofuNIMitXMnVzEW&export=media','first_image' => 'https://drive.google.com/uc?id=19C7Qe5zK_fD4MRWSQnhymYO3weD-bkhu&export=media','second_image' => 'https://drive.google.com/uc?id=1_w39EMFlMrwNuEzeXmXXObwOm7Z9GSJo&export=media','category_id' => '13','subcategory_id' => '12','childcategory_id' => '7','name' => 'grilled chicken','slug' => 'grilled-chicken','description' => 'Grilled Chicken Breast is a quick meal with tender juicy chicken in a flavorful marinade. It\'s extra quick to make and perfect to enjoy on its own, add to pasta, or even put on top of a salad! A quick and flavorful marinade and an even quicker grill time means this is meal on the table in no time at','price' => '88','price_status' => 'fixed','product_condition' => 'likenew','listing_location' => 'tt','country_id' => '11','state_id' => '238','city_id' => '6543','phone_number' => '77','published' => '0','link' => 'https://www.youtube.com/watch?v=oWXlmAeqoUE','created_at' => '2022-05-24 17:45:45','updated_at' => '2022-05-28 13:38:40'),
                array('id' => '19','user_id' => '5','featured_image' => 'https://drive.google.com/uc?id=1RB19UBDPhlxcsIf6DXM4Rf-nMVQOoHiO&export=media','first_image' => 'https://drive.google.com/uc?id=1FVVdnEJ9-0sWOuUGLU9cUb5J0iBlDmE9&export=media','second_image' => 'https://drive.google.com/uc?id=1e56Sdx_a5Bsg8yuTCtChzKg0L5PgKKPO&export=media','category_id' => '13','subcategory_id' => '12','childcategory_id' => '7','name' => 'test2','slug' => 'test2','description' => 'test2','price' => '66','price_status' => 'fixed','product_condition' => 'likenew','listing_location' => 'ttt','country_id' => '11','state_id' => '238','city_id' => '6542','phone_number' => '666','published' => '1','link' => 'https://www.youtube.com/watch?v=G4U09p-TE04','created_at' => '2022-05-27 21:06:23','updated_at' => '2022-05-27 21:06:23'),
                array('id' => '20','user_id' => '21','featured_image' => 'https://drive.google.com/uc?id=1c-xcV4nReeVbtmvHqP3S1dU6ln4iaMRf&export=media','first_image' => 'https://drive.google.com/uc?id=10PnFbD1VtLaxy4eLeisdlfijQzO3tGG8&export=media','second_image' => 'https://drive.google.com/uc?id=18Kb6imCd-7LhkLP2bYO6kBYeqg1u4AHC&export=media','category_id' => '14','subcategory_id' => '13','childcategory_id' => '9','name' => 'drink test','slug' => 'drink-test','description' => 'drink test','price' => '66','price_status' => 'fixed','product_condition' => 'heavilyused','listing_location' => 'uuu','country_id' => '11','state_id' => '240','city_id' => '6546','phone_number' => '999999','published' => '0','link' => 'https://www.youtube.com/watch?v=ZMTOyDfMl8c','created_at' => '2022-05-28 10:23:42','updated_at' => '2022-05-28 10:23:42'),
                array('id' => '21','user_id' => '6','featured_image' => 'https://drive.google.com/uc?id=1O4L2rJ2wAPog57yxBv1-0SnVbmvX3Pdx&export=media','first_image' => 'https://drive.google.com/uc?id=1IEuSzvqPDP9S4YbxvAOLkUVprsBJBVcB&export=media','second_image' => 'https://drive.google.com/uc?id=1iO2GIlZ7f-NxvUyaQa2-bfcm0A2QiDQm&export=media','category_id' => '14','subcategory_id' => '13','childcategory_id' => '9','name' => 'drink fresh','slug' => 'drink-fresh','description' => 'drink fresh','price' => '44','price_status' => 'fixed','product_condition' => 'likenew','listing_location' => 'yyyy','country_id' => '11','state_id' => '238','city_id' => '6542','phone_number' => '777','published' => '1','link' => 'https://www.youtube.com/watch?v=lfd2uclYnY0','created_at' => '2022-05-28 12:22:54','updated_at' => '2022-05-28 13:34:16'),
                array('id' => '22','user_id' => '6','featured_image' => 'https://drive.google.com/uc?id=1illbxao8Y2bjcIaiwiz-YrwWchsHMuTY&export=media','first_image' => 'https://drive.google.com/uc?id=1es3fmVzWW53_93oGRNb05070xCPinTCy&export=media','second_image' => 'https://drive.google.com/uc?id=1nX-iJZQMNVEkt_X1BHyNd2YZNGmsuJJ4&export=media','category_id' => '20','subcategory_id' => '15','childcategory_id' => '11','name' => 'uuuuuuuuu','slug' => 'uuuuuuuuu','description' => 'oooooooooo','price' => '55','price_status' => 'negoitable','product_condition' => 'likenew','listing_location' => 'yyyy','country_id' => '14','state_id' => NULL,'city_id' => NULL,'phone_number' => '777','published' => '1','link' => 'ttt','created_at' => '2022-05-28 13:54:57','updated_at' => '2022-05-28 13:54:57')
           
            );
            DB::table('advertisments')->insert($advertisments);
    }
}
